export const API_ENDPOINTS = {
    USER: {
        REGISTER: "/register",
        LOGIN: "/login",
        GOOGLE_LOGIN: "/auth/google",
        VERIFY_OTP: "/verify-otp",
        RESEND_OTP: "/resend-otp",
        LOGOUT: "/logout",
        REFRESH_TOKEN: "/refresh-token",
        PROFILE: "/profile",
        CHANGE_PASSWORD: "/change-password",
        FORGOT_PASSWORD: "/forgot-password",
        VERIFY_FORGOT_OTP: "/verify-forgot-otp",
        RESET_PASSWORD: "/reset-password",
        PACKAGES: "/packages",
        VERIFY_EMAIL_OTP: "/verify-email-otp",
        CHECK_EMAIL: "/check-email",
        CATEGORY: "/category",
        CREATE_BOOKING: "/bookings/create",
        WALLPAPERS: "/wallpapers",

    },
    ADMIN: {
        LOGIN: "/admin/login",
        LOGOUT: "/admin/logout",
        REFRESH_TOKEN: "/admin/refresh-token",
        USERS: "/admin/users",
        CREATORS: "/admin/creators",
        CATEGORY: "/admin/category",
        SUBSCRIPTION: "/admin/subscription",
        WALLPAPERS: "/admin/wallpapers",

    },
    CREATOR: {
        REGISTER: "/creator/register",
        LOGIN: "/creator/login",
        LOGOUT: "/creator/logout",
        REFRESH_TOKEN: "/creator/refresh-token",
        FORGOT_PASSWORD: "/creator/forgot-password",
        VERIFY_FORGOT_OTP: "/creator/verify-forgot-otp",
        RESET_PASSWORD: "/creator/reset-password",
        CHECK_EMAIL: "/creator/check-email",
        VERIFY_OTP: "/creator/verify-otp",
        RESEND_OTP: "/creator/resend-otp",
        PROFILE: "/creator/profile",
        PACKAGE: "/creator/package",
        CATEGORY: "/creator/category",
        WALLPAPER: "/creator/wallpaper",
    },
    UPLOAD: {
        VIEW_URL: "/upload/view-url",
        PRESIGN: "/upload/presign",
    },
};
