export const BACKEND_ROUTES = {
  BASE: "/api",
  USER: {
    REGISTER: "/register",
    VERIFY_OTP: "/verify-otp",
    RESEND_OTP: "/resend-otp",
    LOGIN: "/login",
    REFRESH_TOKEN: "/refresh-token",
    FORGOT_PASSWORD: "/forgot-password",
    VERIFY_FORGOT_OTP: "/verify-forgot-otp",
    RESET_PASSWORD: "/reset-password",
    GOOGLE_AUTH: "/auth/google",
    LOGOUT: "/logout",
    PROFILE: "/profile",
    CHANGE_PASSWORD: "/change-password",
    PACKAGES: "/packages",
    PACKAGE_DETAIL: "/packages/:id",
    VERIFY_EMAIL_OTP: "/verify-email-otp",
    CHECK_EMAIL: "/check-email",
    CATEGORY: "/category",
  },
  CREATOR: {
    BASE: "/creator",
    REGISTER: "/register",
    LOGIN: "/login",
    REFRESH_TOKEN: "/refresh-token",
    FORGOT_PASSWORD: "/forgot-password",
    VERIFY_FORGOT_OTP: "/verify-forgot-otp",
    RESET_PASSWORD: "/reset-password",
    CHECK_EMAIL: "/check-email",
    VERIFY_OTP: "/verify-otp",
    RESEND_OTP: "/resend-otp",
    LOGOUT: "/logout",
    PROFILE: "/profile",
    PACKAGE: "/package",
    PACKAGE_DETAIL: "/package/:packageId",
    CATEGORY: "/category",
    SUBSCRIPTION: "/subscription",
    SUBSCRIPTION_BUY: "/subscription/buy",
    WALLPAPER:"/wallpaper"
  },
  ADMIN: {
    BASE: "/admin",
    LOGIN: "/login",
    REFRESH_TOKEN: "/refresh-token",
    LOGOUT: "/logout",
    USERS: "/users",
    CREATORS: "/creators",
    APPROVE_CREATOR: "/creators/:id/approve",
    REJECT_CREATOR: "/creators/:id/reject",
    USER_STATUS: "/users/:userId/status",
    CREATOR_STATUS: "/creators/:creatorId/status",
    CATEGORY: "/category",
    CATEGORY_DETAIL: "/category/:categoryId",
    SUBSCRIPTION: "/subscription",
    SUBSCRIPTION_DETAIL: "/subscription/:subscriptionId",
  },
  UPLOAD: {
    BASE: "/upload",
    PRESIGN: "/presign",
    VIEW_URL: "/view-url",
    VIEW: "/view",
  },
};
